# ~/.bashrc: executed by bash(1) for non-login shells.

# Note: PS1 and umask are already set in /etc/profile. You should not
# need this unless you want different defaults for root.
# PS1='${debian_chroot:+($debian_chroot)}\h:\w\$ '
# umask 022

# You may uncomment the following lines if you want `ls' to be colorized:
export LS_OPTIONS='--color=auto'
# eval "$(dircolors)"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'
#
# Some more alias to avoid making mistakes:
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'

PATH=/root/tools/nvim/bin:/root/tools/nodejs/bin:/root/bin:/root/.emacs.d/bin:/root/cmake-3.25.0-linux-x86_64/bin:$PATH

function dec(){
	 decompressor decompress $@ | iconv -f gbk -t utf8
}

function sc(){
	tmux a || tmux
}

function nj {
	ninja $@
}

function cn {
	cmake -GNinja ..
}

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

alias vi=nvim

ulimit -c unlimited
source /w_code/My-Linux-Config/scripts/shell/git-completion.bash
source /w_code/My-Linux-Config/scripts/shell/git-prompt.sh

export PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '
